export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_VOLUNTEERS = 'GET_VOLUNTEERS';
export const GET_NEEDY = 'GET_NEEDY';
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SUBMIT_VERIFCATION_DOCTOR = 'SUBMIT_VERIFICATION_DOCTOR';
export const ACCEPT_VERIFICATION_DOCTOR = 'ACCEPT_VERIFICATION_DOCTOR';
